name: PR Version Check

on:
  pull_request:
    types: [opened, synchronize, reopened]
    branches:
      - main

jobs:
  version-check:
    uses: ./.github/workflows/version-check-reusable.yml
    with:
      gradle-file-path: 'build.gradle'  # Can be customized
      auto-update-version: true             # Enable auto-update
      version-increment: 'patch'            # Can be 'major', 'minor', or 'patch'
    secrets:
      token: ${{ secrets.GITHUB_TOKEN }}