name: Increment Version
on:
  pull_request:
    types: [opened, synchronize]
jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Increment version
        uses: sardul3/gradle-version-incrementer@v1.0.1
        with:
          file-path: 'build.gradle'
          increment-type: 'patch'