name: Increment Version
on:
  pull_request:
    types: [opened, synchronize]
permissions:
  contents: write
  pull-requests: write
jobs:
  increment-version:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: sardul3/gradle-version-incrementer@1.0.8
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          file-path: 'build.gradle'
          increment-type: 'patch'
          mode: 'update-file'